### PR TITLE
Remove falsy tests

### LINKED ISSUE #11: Remove falsy tests which don't align with interface specification
The interface specification clearly documents that it expects, w.r.t. the `other` argument, a Term for `Term#equals(Term other)` and a Quad for `Quad#equal(Quad other)`. The behavior for unexpected types is not defined, i.e., whether it should return false or throw an Error: [#132](https://github.com/rdfjs/representation-task-force/issues/132) and [#133](https://github.com/rdfjs/representation-task-force/issues/133).

Until these issues are resolved, the falsy tests in this suite should not make assumptions about undefined behavior. Let's get this suite aligned with the specification for now and table such tests until we can come to a decision about the interface.

### PR DESCRIPTION
**Pull request by blake-regalia**
Closes #11

### CODE REVIEW

**Comment by bergos** [comment]
There where also some opinions against this. As it's not clear if we keep the PR at the end, let's discuss this in the next call.

**Comment by blake-regalia** [comment]
Hmm my point is that as it stands, the test suite is actually enforcing undefined behavior. That does not align with the interface spec. It's okay if people end up amending the spec but these test cases were not even PR'd for approval. Can we compromise by at least commenting them out for now? Right now the suite is actually prohibiting me from publishing for this reason.

**Comment by bergos** [comment]
The compromise would be OK for me, but I have no idea how to handle that with sem versioning. As an alternative you could use a temporary git dependency in your project.

Also if you are talking about a full release and not just a beta or release candidate, I'm not sure if you do yourself a favor. The outcome of the discussion could be also that we change the spec. That would be a breaking change in your code.

**Comment by vhf** [comment]
> The compromise would be OK for me, but I have no idea how to handle that with sem versioning.

If I understand correctly, the goal of this package is to implement a spec. It currently deviates from the spec by enforcing undefined behaviour.

According to semver I'd say this is a patch version (*internal change that fixes incorrect behavior* aka bugfix)?

**Comment by bergos** [comment]
We never discussed this, but in my opinion it's not one way from the spec to this repo. If we find differences or gaps, first we have to decide where to make the fix. That decision was not made yet.

So semver would need to cover a possible future patch version, not an actual patch version. IMHO a git branch is the right tool for this case.

@RubenVerborgh you have any feedback? It's your code from 417efb2cfc1013e6c4f61818248264afe562fc5b which I have merged.

**Comment by RubenVerborgh** [comment]
I remember a discussion with @blake-regalia, where he was convinced: https://github.com/rdfjs/representation-task-force/issues/132#issuecomment-442707546

**Comment by blake-regalia** [comment]
@RubenVerborgh I'm still on the fence, I'd like to hear what others have to say on the call. Let's keep this PR and the issue open for now and i'll just use the branch as @bergos suggested.

**Comment by RubenVerborgh** [comment]
Obsoleted by proposed resolution https://github.com/rdfjs/representation-task-force/issues/142.

**Pull request closed without merging**
